[package]
name = "sw-ibm1130-emulator"
version = "0.1.0"
edition = "2024"
description = "IBM 1130 Emulator: instruction execution semantics"
license = "MIT"

[dependencies]
sw-isa-core = { path = "/Users/mike/github/sw-langtools/sw-isa-core" }
sw-ibm1130-isa = { path = "../sw-ibm1130-isa" }

[dev-dependencies]
sw-ibm1130-asm = { path = "../sw-ibm1130-asm" }
